# Generated by Django 4.0.5 on 2022-08-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companydouments',
            fields=[
                ('documentid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, default=None, null=True)),
                ('addhar', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('pan', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('gst', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/images')),
                ('mes', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Companyprofiles',
            fields=[
                ('companyid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, default=None, null=True)),
                ('company_name', models.CharField(blank=True, max_length=500, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=25, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=15, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('company_street', models.CharField(blank=True, max_length=200, null=True)),
                ('company_city', models.CharField(blank=True, max_length=200, null=True)),
                ('company_state', models.CharField(blank=True, max_length=200, null=True)),
                ('company_pin', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countorders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_new_application', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('total_old_application', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('total_cancel_application', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('total_application_amount', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('total_revenue', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('pendingvalue', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('adminuser', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('roletype', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('userid', models.IntegerField(blank=True, default=None, null=True)),
                ('feedbackid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoiceid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, default=None, null=True)),
                ('invoiceditems', models.TextField(blank=True, null=True)),
                ('invoicedamount', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('invoicedamountwithtax', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('taxpercentage', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monthdata',
            fields=[
                ('monthid', models.AutoField(primary_key=True, serialize=False)),
                ('total_order', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('complete_order', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('pending_order', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('cancel_order', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orderoverview',
            fields=[
                ('orderoverviewid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, default=None, null=True)),
                ('open_order', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('queries_in_uploading_document', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('pending_documents', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('plan_expire', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('documents', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orderrequirementdocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('backenduser', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('accountuser', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('adminuser', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('paymentstatus', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('status1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('roletype', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('servicename', models.CharField(max_length=100)),
                ('directorsphotograph', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/images')),
                ('directorspancard', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/images')),
                ('idproof', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/images')),
                ('dinofdirectors', models.FileField(blank=True, default=None, null=True, upload_to='uploads/documents')),
                ('electricitybill', models.FileField(blank=True, default=None, null=True, upload_to='uploads/documents')),
                ('residentialproof', models.FileField(blank=True, default=None, null=True, upload_to='uploads/documents')),
                ('date', models.DateField(auto_now=True)),
                ('moa', models.FileField(blank=True, default=None, null=True, upload_to='uploads/documents')),
                ('aoa', models.FileField(blank=True, default=None, null=True, upload_to='uploads/documents')),
                ('invoicedocument', models.FileField(blank=True, default=None, null=True, upload_to='uploads/documents')),
                ('certificate', models.FileField(blank=True, default=None, null=True, upload_to='uploads/documents')),
                ('documentstatus', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('reason', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orderrequirements',
            fields=[
                ('orderrequirementsid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, default=None, null=True)),
                ('servicename', models.CharField(max_length=100)),
                ('bussinessoperationalstatus', models.CharField(blank=True, max_length=500, null=True)),
                ('ageofbussiness', models.CharField(blank=True, max_length=500, null=True)),
                ('numberofemployees', models.CharField(blank=True, max_length=500, null=True)),
                ('bussinessarea_category', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofiles',
            fields=[
                ('userprofilesid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, default=None, null=True)),
                ('first_name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('street', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('pin', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
            ],
        ),
    ]
