# Generated by Django 4.1 on 2022-08-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataformApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydouments',
            name='mes',
        ),
        migrations.AlterField(
            model_name='companydouments',
            name='addhar',
            field=models.FileField(default='uploads/images/default-image_450_oUOR6yd.png', upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='companydouments',
            name='gst',
            field=models.FileField(default='uploads/images/default-image_450_oUOR6yd.png', upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='companydouments',
            name='pan',
            field=models.FileField(default='uploads/images/default-image_450_oUOR6yd.png', upload_to='uploads/images'),
        ),
    ]
