# Generated by Django 4.1 on 2022-08-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataformApp', '0002_remove_companydouments_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydouments',
            name='addhar',
            field=models.FileField(default='uploads/images/default-image_450.png', upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='companydouments',
            name='gst',
            field=models.FileField(default='uploads/images/default-image_450.png', upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='companydouments',
            name='pan',
            field=models.FileField(default='uploads/images/default-image_450.png', upload_to='uploads/images'),
        ),
    ]
