# Generated by Django 4.1 on 2022-08-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataformApp', '0003_alter_companydouments_addhar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydouments',
            name='addhar',
            field=models.FileField(upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='companydouments',
            name='gst',
            field=models.FileField(upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='companydouments',
            name='pan',
            field=models.FileField(upload_to='uploads/images'),
        ),
    ]
