# Generated by Django 4.1 on 2022-08-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataformApp', '0005_alter_companydouments_addhar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydouments',
            name='addhar',
            field=models.FileField(blank=True, default=None, max_length=200, null=True, upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='companydouments',
            name='gst',
            field=models.FileField(blank=True, default=None, max_length=200, null=True, upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='companydouments',
            name='pan',
            field=models.FileField(blank=True, default=None, max_length=200, null=True, upload_to='uploads/images'),
        ),
    ]
