# Generated by Django 4.0.5 on 2022-09-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataformApp', '0007_alter_companydouments_addhar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrequirementdocuments',
            old_name='aoa',
            new_name='incorporationdoc',
        ),
        migrations.RenameField(
            model_name='orderrequirementdocuments',
            old_name='dinofdirectors',
            new_name='otherdoc',
        ),
        migrations.RenameField(
            model_name='orderrequirementdocuments',
            old_name='moa',
            new_name='partnershipdeed',
        ),
        migrations.RenameField(
            model_name='orderrequirementdocuments',
            old_name='residentialproof',
            new_name='photoofpremises',
        ),
        migrations.RenameField(
            model_name='orderrequirementdocuments',
            old_name='directorspancard',
            new_name='photoofproduct',
        ),
        migrations.RenameField(
            model_name='orderrequirementdocuments',
            old_name='idproof',
            new_name='rentagrement',
        ),
        migrations.AddField(
            model_name='companydouments',
            name='other',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/images'),
        ),
    ]
