# Generated by Django 4.0.5 on 2022-10-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataformApp', '0008_rename_aoa_orderrequirementdocuments_incorporationdoc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='street',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
