# Generated by Django 4.0.5 on 2022-10-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataformApp', '0009_alter_userprofiles_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequirementdocuments',
            name='directorsphotograph',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='orderrequirementdocuments',
            name='photoofproduct',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='orderrequirementdocuments',
            name='rentagrement',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='uploads/images'),
        ),
    ]
