# Generated by Django 4.0.5 on 2022-10-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataformApp', '0010_alter_orderrequirementdocuments_directorsphotograph_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usertoken',
            fields=[
                ('tokenid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, default=None, null=True)),
                ('token', models.CharField(max_length=500)),
            ],
        ),
    ]
