# Generated by Django 4.0.5 on 2022-10-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataformApp', '0011_usertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mytoken',
            fields=[
                ('tokenid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, default=None, null=True)),
                ('token', models.CharField(default=None, max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Usertoken',
        ),
    ]
