# Generated by Django 4.0.5 on 2022-10-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataformApp', '0012_mytoken_delete_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytoken',
            name='username',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
