# Generated by Django 4.0.5 on 2022-10-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataformApp', '0013_mytoken_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myuserid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
