# Generated by Django 4.0.5 on 2022-10-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataformApp', '0014_myuserid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myemailid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Olddocs',
            fields=[
                ('docid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('docname', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('docs', models.FileField(blank=True, default=None, null=True, upload_to='uploads/images')),
            ],
        ),
        migrations.CreateModel(
            name='Olduserdata',
            fields=[
                ('oldid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('companyname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('applicationname', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
    ]
