# Generated by Django 4.0.5 on 2022-11-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataformApp', '0015_myemailid_olddocs_olduserdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olduserdata',
            name='companyname',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='olduserdata',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
