# Generated by Django 4.0.5 on 2022-11-07 09:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dataformApp', '0016_alter_olduserdata_companyname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olddocs',
            name='document',
            field=models.FileField(default=datetime.datetime(2022, 11, 7, 9, 4, 53, 482268, tzinfo=utc), upload_to='uploads/documents'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='olddocs',
            name='docs',
            field=models.FileField(default=datetime.datetime(2022, 11, 7, 9, 5, 7, 294628, tzinfo=utc), upload_to='uploads/images'),
            preserve_default=False,
        ),
    ]
