# Generated by Django 4.0.5 on 2022-11-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataformApp', '0017_olddocs_document_alter_olddocs_docs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myemail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
    ]
