# Generated by Django 4.0.5 on 2022-11-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataformApp', '0018_myemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myemail',
        ),
    ]
