# Generated by Django 4.0.5 on 2022-11-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataformApp', '0019_delete_myemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olddocs',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='olduserdata',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
