# Generated by Django 4.0.5 on 2023-06-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataformApp', '0020_alter_olddocs_email_alter_olduserdata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='olddocs',
            name='companyname',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
