# Generated by Django 4.0.5 on 2022-08-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, default=None, null=True)),
                ('servicename', models.CharField(max_length=100)),
                ('order_amount', models.CharField(max_length=25)),
                ('isPaid', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('order_payment_id', models.CharField(max_length=100)),
            ],
        ),
    ]
